FROM nginx

MAINTAINER Ewa Dadacz <ewa.dadacz@gmail.com>

# RUN rm /usr/share/nginx/html/*

COPY configs/nginx.conf /etc/nginx/nginx.conf

# COPY docker-entrypoint /
# RUN chmod +x docker-entrypoint
# ENTRYPOINT ["docker-entrypoint"]

# CMD ["nginx", "-g", "daemon off;"]

